name: Publish

on:
  push:
    branches:
    - main
    - track/**
    - test-ci

jobs:

  get-rock-paths-modified:
    name: Get rockcraft paths modified
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/get-rocks-modified.yaml@ci/test
    with:
      base-ref: ${{ github.ref_name }}
    permissions:
      pull-requests: read
